version: '3'

services:
  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tezos
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d tezos"]
      interval: 10s
      retries: 5

