// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Delegation struct {
	ID        int64     `json:"id"`
	Delegator string    `json:"delegator"`
	Timestamp time.Time `json:"timestamp"`
	Amount    int64     `json:"amount"`
	Level     int64     `json:"level"`
}
